import → importer
Avoid error caused by use of keyword:

    from piws.import.subjects import Subjects
                   ^
SyntaxError: invalid syntax